# -*- coding: utf-8 -*-
"""Vernam Cipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eUJJdc-aKD1bW25xk5m30cy1MOkIJj1i

## **VERNAM CIPHER**
"""

# Convert text ke binary
def text_to_binary(text):
    binary_text = ''.join(format(ord(char), '08b') for char in text)
    return binary_text

# Enkripsi
def encrypt(plaintext_binary, key_binary):
    ciphertext_binary = ""
    for i in range(len(plaintext_binary)):
        ciphertext_binary += str(int(plaintext_binary[i]) ^ int(key_binary[i % len(key_binary)]))
    return ciphertext_binary

# Dekripsi
def decrypt(ciphertext_binary, key_binary):
    plaintext_binary = ""
    for i in range(len(ciphertext_binary)):
        plaintext_binary += str(int(ciphertext_binary[i]) ^ int(key_binary[i % len(key_binary)]))
    return plaintext_binary

# Convert binary ke text
def binary_to_text(binary_text):
    text = ""
    for i in range(0, len(binary_text), 8):
        byte = binary_text[i:i+8]
        text += chr(int(byte, 2))
    return text

if __name__ == '__main__':
    print("===========================================================================================================")
    print("================================== Vernam Enkripsi / Dekripsi =============================================")
    print(" ")
    def menu():
        print("Menu:")
        print("\t1 - Enkripsi")
        print("\t2 - Dekripsi")
        print("\t3 - Keluar")

    # Main program loop
    while True:
        menu()
        choice = input("Masukkan pilihan Anda (1/2/3): ")

        if choice == "1":
            plaintext = input("Masukkan plaintext: ")
            key = input("Masukkan key: ")
            print('---------------------')
            print('Mengenkripsi plaintext...')
            print('---------------------')

            plaintext_binary = text_to_binary(plaintext)
            key_binary = text_to_binary(key)

            print(f"{plaintext} : { ' '.join([plaintext_binary[i:i+8] for i in range(0, len(plaintext_binary), 8)])}")
            print(f"{key} : {' '.join([key_binary[i:i+8] for i in range(0, len(key_binary), 8)])}")

            ciphertext_binary = encrypt(plaintext_binary, key_binary)
            ciphertext = binary_to_text(ciphertext_binary)

            print("Proses XOR:")
            print("Biner :", ' '.join([plaintext_binary[i:i+8] for i in range(0, len(plaintext_binary), 8)]))
            print("Key   :", ' '.join([key_binary[i % len(key_binary):i % len(key_binary) + 8] for i in range(0, len(plaintext_binary), 8)]))
            print("      ⊕")
            print("Hasil :", ' '.join([ciphertext_binary[i:i+8] for i in range(0, len(ciphertext_binary), 8)]))
            print('---------------------')
            print("Ciphertext:", ciphertext)
            print('---------------------')
            print()

        elif choice == "2":
            ciphertext = input("Masukkan ciphertext: ")
            key = input("Masukkan key: ")
            print('---------------------')
            print('Mendekripsi ciphertext...')
            print('---------------------')

            ciphertext_binary = text_to_binary(ciphertext)
            key_binary = text_to_binary(key)

            print(f"{ciphertext} : {' '.join([ciphertext_binary[i:i+8] for i in range(0, len(ciphertext_binary), 8)])}")
            print(f"{key} : {' '.join([key_binary[i:i+8] for i in range(0, len(key_binary), 8)])}")

            plaintext_binary = decrypt(ciphertext_binary, key_binary)
            plaintext = binary_to_text(plaintext_binary)

            print("Proses XOR:")
            print("Biner :", ' '.join([ciphertext_binary[i:i+8] for i in range(0, len(ciphertext_binary), 8)]))
            print("Key   :", ' '.join([key_binary[i % len(key_binary):i % len(key_binary) + 8] for i in range(0, len(ciphertext_binary), 8)]))
            print("      ⊕")
            print("Hasil :", ' '.join([plaintext_binary[i:i+8] for i in range(0, len(plaintext_binary), 8)]))
            print('---------------------')
            print("Plaintext:", plaintext)
            print('---------------------')
            print()

        elif choice == "3":
            print("Keluar...")
            break

        else:
            print("Pilihan tidak valid. Silakan pilih 1, 2, atau 3.")
            print()

    print(" ")
    print("============================================ SELESAI ==========================================================")
    print("===============================================================================================================")